[package]
name = "weather_cli_app"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
dotenvy = "0.15.7"
reqwest = { version = "0.12.15", features = ["blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
